FROM bitnami/minio:latest

ENV MINIO_ROOT_USER=mirza
ENV MINIO_ROOT_PASSWORD=test1234

EXPOSE 9000 9001

WORKDIR /data

VOLUME /data

CMD ["minio", "server", "/data", "--address", ":9000", "--console-address", ":9001"]
