FROM bitnami/minio:latest

ENV MINIO_ROOT_USER=mirza
ENV MINIO_ROOT_PASSWORD=test1234

EXPOSE 9000 9001

WORKDIR /bitnami/minio/data

VOLUME /bitnami/minio/data

CMD ["minio", "server", "/bitnami/minio/data", "--address", "127.0.0.1:9000", "--console-address", "127.0.0.1:9001"]
