FROM bitnami/minio:latest

ENV MINIO_ACCESS_KEY=mirza
ENV MINIO_SECRET_KEY=test1234

EXPOSE 9000 9001

WORKDIR /data

VOLUME /data

CMD ["minio", "server", "--address", ":9000", "--console-address", ":9001"]
